
import "./globals.css";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="font-xp">
        {children}
      </body>
    </html>
  );
}